"""Machine learning components."""

# DataLoader system
from .dataloaders import (
    AbstractDataLoader,
    Dataset,
    DataSource,
    TransformRegistry,
    UniversalTransform,
)
from .models import (
    ArtifactModelProvider,
    CheckpointModelProvider,
    CheckpointReference,
    CheckpointResolver,
    Model,
    ModelArtifactReference,
    ModelArtifactResolver,
    ModelConfig,
    ModelProvider,
    ResolvedCheckpoint,
    ResolvedModelArtifact,
)
from .predictors import (
    BasePredictionResult,
    CallableModel,
    GenericPredictionResult,
    HumanReadablePredictionResult,
    PredictionInterface,
    PredictorProtocol,
    SamPredictionResult,
    SamuraiPredictionResult,
)
from .registry import ModelProviderRegistry, PredictorRegistry
from .trainers import (
    EpochResult,
    EvaluationConfig,
    EvaluationContext,
    EvaluationResult,
    EvaluationStatus,
    Evaluator,
    Issue,
    IssueSeverity,
    Trainer,
    TrainingConfig,
    TrainingContext,
    TrainingResult,
    TrainingStatus,
    TrainingStopReason,
)

__all__ = [
    "ModelProviderRegistry",
    "PredictorRegistry",
    "Model",
    "ModelArtifactReference",
    "ModelArtifactResolver",
    "ModelConfig",
    "ModelProvider",
    "CheckpointModelProvider",
    "CheckpointReference",
    "CheckpointResolver",
    "ArtifactModelProvider",
    "ResolvedCheckpoint",
    "ResolvedModelArtifact",
    "PredictionInterface",
    "PredictorProtocol",
    "CallableModel",
    # Result classes
    "BasePredictionResult",
    "HumanReadablePredictionResult",
    "GenericPredictionResult",
    "SamPredictionResult",
    "SamuraiPredictionResult",
    # DataLoader system
    "DataSource",
    "Dataset",
    "AbstractDataLoader",
    "UniversalTransform",
    "TransformRegistry",
    # Training and evaluation
    "EpochResult",
    "EvaluationConfig",
    "EvaluationContext",
    "EvaluationResult",
    "EvaluationStatus",
    "Evaluator",
    "Issue",
    "IssueSeverity",
    "Trainer",
    "TrainingConfig",
    "TrainingContext",
    "TrainingResult",
    "TrainingStatus",
    "TrainingStopReason",
]
